# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sHudMONHQpB3StF19p6DpWlDnoiy5ZWs
"""

# @title Default title text
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Link
https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv
"""

df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

df.head()

df.describe()

"""Question 1
What is the correlation between features in the dataset.And what two features have very strong correlation with the independent variable ?Justify your answer.
"""

df.corr()

sns.heatmap(df.corr(),annot=True)

"""Skin thickness and Blood pressure are strongly relate with independent variable 'outcome' because thses are nearer to 1 with outcome .

Question 2
Which feature has more outliers.Explain with a visualization.
"""

df.boxplot()

df.boxplot("Pregnancies")

df.boxplot("Glucose")

df.boxplot("BloodPressure")

df.boxplot("SkinThickness")

df.boxplot("Insulin")

df.boxplot("BMI")

df.boxplot("DiabetesPedigreeFunction")

df.boxplot("Age")

df.boxplot("Outcome")

"""Insulin has mor outliers

Question 3
In which age group majority of people have diabetes?Make a visualization to validate your finding.
"""

x="DiabetesPedigreeFunction"
y="Age"
plt.bar(x,y,color='y',data=df)
plt.title('Bar graph')
plt.ylabel('Age')
plt.xlabel('DiabetesPedigreeFunction')